### ISSUE TITLE
'foldlevelstart' and 'foldlevel' in vimrc not honored

### ISSUE THREAD

**Issue by jefferai** [Konfekt/FastFold#25] opened 2015-10-14 18:46 UTC
I have
```
set foldlevelstart=10
set foldlevel=10
````
in my .vimrc, but it's not being honored; I go into a file and everything starts out folded. A `verbose set foldlevel` claims that the value is 10, but if I run `set foldlevel=10` then most folds are expanded as expected. This behavior only started after installing FastFold.

If there is a way to adjust this that I missed in the documentation, apologies. Also let me know if I should make it a separate issue.

Thanks!

**Comment by Konfekt** [comment] 2015-10-14 21:16
Hi Jeff, 

Not reproducible over here. On opening a TeX file, everything is folded with
```
set foldlevelstart=10
set foldlevel=10
```
and open with
```
set foldlevelstart=0
set foldlevel=0
```
Perhaps you could pass me the file in question? Did you try disabling, by divide and conquer, possibly interfering plugins?

Do you use `vim-stay` or alike that restores folds on opening a file? 

As a workaround, try
```
autocmd BufWinEnter * setlocal foldlevel=10
```
or perhaps
```
autocmd VimEnter * autocmd BufWinEnter * setlocal foldlevel=10
```
Does that change anything?

**Comment by jefferai** [comment] 2015-10-14 21:52
After a lot more weird behavior, some of which persisted after uninstalling FF, I deleted the contents of `~/.vim/view/` and things are working sanely again. I think there was just some correlation timewise between things getting strange and installing FF.

Do you know, is this common behavior -- the views getting into a bad state?

**Comment by kopischke** [comment] 2015-10-15 05:49
View sessions override fold settings on a per file basis, unless you set `viewoptions-=folds` (so do full sessions, BTW, the pertinent setting there is `sessionoptions`). This is a feature, not a bug, as it is the only way to stop Vim resetting all your fold levels at the start of an editing sessions, so I would not be calling that behaviour “bad state” per se, but it can surprise you if you were unaware of it.

**Comment by Konfekt** [comment] 2015-10-15 09:20
Would be interesting to know if Jeff left the folds open before saving the view, for example before quitting the buffer with a mkview autocmd trigger. 

Ok, how about we close this issue, as it is seemingly resolved by deleting `~/.vim/view` and installing FastFold plus vim-stay (which we guarantee to work well together). And reopen as soon as it resurges.

**Closed by Konfekt** 2015-10-15 09:20 UTC

**Comment by jefferai** [comment] 2015-10-15 13:57
Just FYI, since you had some questions:

This is what I had for view management:
```
au BufWinLeave * mkview                                                                                                    
au VimEnter * loadview
```
I found that when I went I opened vim with a file (e.g. `vim blah.go`) and everything was folded, running either `set foldlevel=10` or `set nofoldenable` would cause a visual change for that session, but after I quit (simply `:q`) and re-opened vim, everything would be folded again. If I ran *both* of those commands, when I reopened vim on that file, everything would be unfolded. But at times everything would re-fold itself.

I don't really know what was going on but it does seem like something was causing the saved views to either be bad or not update properly.

I'll try vim-stay instead!

**Comment by Konfekt** [comment] 2015-10-15 17:24
On `BufWinLeave` FastFold restores the previous foldmethod, say `syntax`. But your `mkview` autocmd probably comes to early, before that of FastFold restoring the `syntax` foldmethod. Then the unfolded manual folds are saved and restored, and probably `set foldlevel=10` has no effect anymore.

But `vim-stay` takes precautions and is meant to work out of the box with `FastFold`.
